site_name: ALTERNATIVE Platform Documentation
site_url: https://platform.alternative-project.eu
repo_url: https://github.com/ALTERNATIVE-EU/alternative.github.io
repo_name: ALTERNATIVE-EU/alternative.github.io

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
#    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.follow

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - abbr
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - User guide:
      - Getting started: user-guide/getting-started.md
      - Web Interface:
          - Introduction: user-guide/ckan/overview.md
          - Users, Organizations, and Authorization: user-guide/ckan/users.md
          - Datasets, Resources, and Groups: user-guide/ckan/datasets.md
          - Metadata: user-guide/ckan/metadata.md
          - API: user-guide/ckan/api.md
      - JupyterHub:
          - Introduction: user-guide/jupyterhub/overview.md
          - File System: user-guide/jupyterhub/filesystem.md
          - Environments: user-guide/jupyterhub/environments.md
          - Alternative Library: user-guide/jupyterhub/library.md
          - R: user-guide/jupyterhub/r.md
          - Bioconductor: user-guide/jupyterhub/bioconductor.md
      - Model Usage: user-guide/model-usage.md
  - Maintainer's guide: 
    - Getting started: maintainer-guide/index.md
    - Architecture:
      - Introduction: maintainer-guide/architecture/overview.md
      - Cloud Infrastructure: maintainer-guide/architecture/cloud-infrastructure.md
      - Kubernetes: maintainer-guide/architecture/kubernetes.md
      - Networking: maintainer-guide/architecture/networking.md
      - Storage: maintainer-guide/architecture/storage.md
    - System Services:
#     - Introduction: system-services/overview.md   
      - AI/ML API:
          - Introduction: maintainer-guide/system-services/ai-ml-api/index.md
          - System Architecture: maintainer-guide/system-services/ai-ml-api/system-architecture.md
          - Data Flow: maintainer-guide/system-services/ai-ml-api/data-flow.md
          - Security:
              - Authentication and Authorization: maintainer-guide/system-services/ai-ml-api/security/authentication-and-authorization.md
              - Encryption: maintainer-guide/system-services/ai-ml-api/security/encryption.md
          - Token Management:
              - CKAN Integration: maintainer-guide/system-services/ai-ml-api/token-management/ckan-integration.md
              - Token Lifecycle: maintainer-guide/system-services/ai-ml-api/token-management/token-lifecycle.md
          - API Usage:
              - Endpoints: maintainer-guide/system-services/ai-ml-api/api-usage/endpoints.md
              - Authentication: maintainer-guide/system-services/ai-ml-api/api-usage/authentication.md
              - Error Handling: maintainer-guide/system-services/ai-ml-api/api-usage/error-handling.md
          - Scalability: maintainer-guide/system-services/ai-ml-api/scalability.md
          - Testing: maintainer-guide/system-services/ai-ml-api/testing.md
    - Administrative Services:
      - Introduction: maintainer-guide/admin-services/overview.md
      - Keycloak: maintainer-guide/admin-services/keycloak.md
      - External DNS: maintainer-guide/admin-services/external-dns.md
      - Cert Manager: maintainer-guide/admin-services/cert-manager.md
      - Ingress Controller: maintainer-guide/admin-services/ingress-controller.md
      - Istio: maintainer-guide/admin-services/istio.md
    - Platform Features:
      - Introduction: maintainer-guide/features/overview.md
      - Data Sharing: maintainer-guide/features/data-sharing.md
      - Extensions: maintainer-guide/features/extensions.md
      - Development Environment: maintainer-guide/features/development-environment.md
      - Multi-user and Collaboration: maintainer-guide/features/multi-user-and-collaboration.md
      - Single Sign-On: maintainer-guide/features/sso.md
      - Elasticity: maintainer-guide/features/elasticity.md
    - Deployment:
      - Platform Deployment: maintainer-guide/deployment/platform.md
      - Envoy Filter: maintainer-guide/deployment/envoy-filter.md
      - AI/ML API: maintainer-guide/deployment/ai-ml-api.md
    - Repositories: maintainer-guide/repositories.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ALTERNATIVE-EU
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ALTERNATIVE_EU
  alternate:
    - name: English
      link: /
      lang: en

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - 'javascripts/extra.js'

metadata:
  description: 'Documentation for the ALTERNATIVE Platform'
  keywords: 'ALTERNATIVE, Platform, Documentation, AI, ML, API'
  author: 'ALTERNATIVE-EU'
  robots: 'index, follow'
  generator: 'MkDocs'
  title_suffix: ' - ALTERNATIVE Platform Documentation'

deploy:
  provider: git
  branch: gh-pages
  message: "Deploying to GitHub Pages"
